#!/usr/bin/env python3
"""One-time audio generator for the Android TTS cache-collision fix.

Reads tools/speak-texts.json (from tools/export-speak-texts.cjs), synthesizes
each text with edge-tts and writes:
  audio/<sha1-12>.mp3      one clip per unique text (skips existing files)
  data/audio-map.js        const AUDIO_MAP = { "<text>": "<file>", ... }

Requires: pip install edge-tts (any venv) and ffmpeg on PATH. Re-runs are
incremental — delete a clip to regenerate it, delete audio/ to regenerate
everything.

Usage: python3 tools/generate-audio.py   (from n5-app/)
"""

import asyncio
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import edge_tts

VOICE = "ja-JP-NanamiNeural"
RATE = "-10%"  # matches the app's live-TTS rate of 0.9
CONCURRENCY = 8

# Synthesis-text overrides (map key and filename stay the original text).
# Bare い gets a click-like burst appended by the engine (sounds like "ik",
# deterministic — regenerating doesn't help); a trailing 。 yields a clean vowel.
PRONUNCIATION_OVERRIDES = {"い": "い。"}

# edge-tts pads every clip with ~230ms leading and ~1s trailing silence; the
# leading pad delays playback audibly in the app, so trim both ends. Cushions
# are generous on purpose: quiet vowel onsets (医→い) sit near the -40dB
# threshold, and Android's audio path swallows the first/last few dozen ms —
# a 50ms cushion made short clips sound chopped. 100ms lead / 250ms trail.
TRIM_FILTER = (
    "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.1,"
    "areverse,"
    "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.25,"
    "areverse"
)


def trim_silence(clip: Path) -> bool:
    with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
        tmp_path = Path(tmp.name)
    try:
        subprocess.run(
            ["ffmpeg", "-y", "-v", "error", "-i", str(clip), "-af", TRIM_FILTER,
             "-c:a", "libmp3lame", "-b:a", "48k", "-ar", "24000", "-ac", "1",
             str(tmp_path)],
            check=True, capture_output=True,
        )
        if tmp_path.stat().st_size < 500:
            raise RuntimeError("trimmed clip suspiciously small")
        tmp_path.replace(clip)
        return True
    except Exception as e:
        tmp_path.unlink(missing_ok=True)
        print(f"TRIM FAIL {clip.name}: {e}", file=sys.stderr)
        return False

ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = ROOT / "audio"
MAP_FILE = ROOT / "data" / "audio-map.js"
TEXTS_FILE = ROOT / "tools" / "speak-texts.json"


def clip_name(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12] + ".mp3"


async def synthesize(sem: asyncio.Semaphore, text: str, out: Path) -> bool:
    async with sem:
        for attempt in range(3):
            try:
                spoken = PRONUNCIATION_OVERRIDES.get(text, text)
                await edge_tts.Communicate(spoken, VOICE, rate=RATE).save(str(out))
                if out.stat().st_size > 1000:
                    return await asyncio.to_thread(trim_silence, out)
                out.unlink(missing_ok=True)
            except Exception:
                out.unlink(missing_ok=True)
            await asyncio.sleep(2 * (attempt + 1))
        print(f"FAIL {text}", file=sys.stderr)
        return False


async def main() -> int:
    texts = json.loads(TEXTS_FILE.read_text("utf-8"))
    AUDIO_DIR.mkdir(exist_ok=True)

    todo = [(t, AUDIO_DIR / clip_name(t)) for t in texts]
    missing = [(t, p) for t, p in todo if not p.exists()]
    print(f"{len(texts)} texts, {len(missing)} to synthesize")

    sem = asyncio.Semaphore(CONCURRENCY)
    results = await asyncio.gather(*(synthesize(sem, t, p) for t, p in missing))
    failed = results.count(False)

    entries = [
        f"{json.dumps(t, ensure_ascii=False)}:{json.dumps(clip_name(t))}"
        for t, p in todo
        if p.exists()
    ]
    MAP_FILE.write_text(
        "// generated by tools/generate-audio.py — do not edit\n"
        "const AUDIO_MAP = {\n" + ",\n".join(entries) + "\n};\n",
        "utf-8",
    )
    total_bytes = sum(p.stat().st_size for _, p in todo if p.exists())
    print(f"map: {len(entries)} entries, audio total {total_bytes / 1e6:.1f} MB, failed: {failed}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
